### ISSUE TITLE
Use of window and console objects in the library while in web worker process

### ISSUE THREAD

**Issue by swapnil0545** [yathit/ydn-db#10]
When I was trying to use the ydn-db in web-worker process, I found that there are many places where window object is being used. 

However worker process do not allow usage of window in it, so we cannot use the library in worker.

Secondly, it is not recommended to use console objects in worker for logging, making it difficult to use the ydn in worker.However console works in chrome webworker but not in safari webworker.

I request to make one library where dom objects(window) and console is not used.

**Comment by swapnil0545** [comment]
I was trying to upgrate to 1.3.3 from 1.0.4 and this issue exists on 1.3.3 on both the prod as well as dev version.

**Comment by yathit** [comment]
Really! I remember I replace all `window` reference. Please provide me a single html page, I will fix.

**Comment by swapnil0545** [comment]
This happens only when I use it inside the worker process as it does not have access to window object. I will create a demo html and give it back to you. 
But you can see the window references(search window)
https://storage.cloud.google.com/ydn-db-d1/1.3.3/ydn.db-isw-core-qry.js
https://storage.cloud.google.com/ydn-db-d1/1.3.3/ydn.db-isw-core-qry-dev.js

**Comment by swapnil0545** [comment]
While in worker script, if I use production version and pass in the options argument as
    var options = {
		mechanisms: ['websql'], // default ordering
        size: 50 * 1024 * 1024 // 50 MB 
    };
new ydn.db.Storage('Information', schema, options);
Then it does not give the "ReferenceError: Can't find variable : window", but it does not even make the schema on the browser(all browser).

But if I remove the options parameter and let the library choose for itslef the size and mechanism.
Then it works well in chrome and gives the "ReferenceError: Can't find variable : window" on Safari
Chrome Version (45.0.2454.101 m) 
Mac OS X Yosemite - Safari 9.0(10601.1.56.2)

**Comment by yathit** [comment]
@swapnil0545  Could you check again with the recent patch?

https://storage.cloud.google.com/ydn-db-d1/1.3.4/ydn.db-isw-core-qry.js
https://storage.cloud.google.com/ydn-db-d1/1.3.4/ydn.db-isw-core-qry-dev.js

Regarding silently failing when `size` option is given, I will let it go until [quota management API](http://www.w3.org/TR/quota-api/) is ready for compatibility reason. `size` option should not be used in modern browsers. According to new concept of quota management, app cannot ask for how much they need, the platform will directly negotiate with user for allow quota.

**Comment by yathit** [comment]
If you want to reduce WebSQL data usage, check out [fixed option](http://dev.yathit.com/api/ydn/db/schema.html) in store schema.

**Comment by swapnil0545** [comment]
@yathit Thank you for the update. It is no more giving me the window reference error.
But It is still not creating the schema on all browsers when I pass 


    var options = {
		mechanisms: ['websql'], // default ordering
    };

to storage options. It is not just the size option.
Here is the demo for that using 1.3.4
http://52.24.87.119/demo2/index.html

**Comment by yathit** [comment]
WebSQL may not be available in web worker.

**Comment by swapnil0545** [comment]
That's sad, I just happen to come across a thread 
https://code.google.com/p/chromium/issues/detail?id=434740

**Comment by yathit** [comment]
Yes. That is very sad news. My hope was Apple will fix indexeddb in ios 9, but still not there yet.

**Comment by swapnil0545** [comment]
Even indexedDB is not available inside webworkers 
https://bugs.webkit.org/show_bug.cgi?id=149953

I don't know what safari developers are thinking. This is going to break our code with the latest updates, with no option to fix.

**Comment by yathit** [comment]
With database async parallel processing are already seperate from ui thread and web worker is not necessary. Just move over all process that use db to main thread. You will find it is better then web worker.

**Comment by JerryLumpkins** [comment]
yathit, We desperately ned to use the webWorkers. We are syncronizing data between the browser and our web server as a background process. Every aspect of modern web design would say to NOT use the primary thread for any db access. Is there any way you can fix your library so that it will work properly with the web workers? We have a large number of users that are completely stopped without that feature. (Swapnil works on our product.)

**Comment by yathit** [comment]
The issue should fix now.
