### ISSUE TITLE
Typescript definition broken or out of date 

### ISSUE THREAD

**Issue by jonrose182** [yathit/ydn-db#100]
I am attempting to use ydn-db within an Angular 2 / Typescript application, but it appears the typescript file is broken or out of date. A few examples of issues I've run into: 

- fullTextCatalogs in the schema definition only takes a single fullTextCatalog entry: 

`interface DatabaseSchemaJson {
  version?: number;
  stores: StoreSchemaJson[];
  fullTextCatalogs?: FullTextCatalog;
}
`

- Search only takes a single argument of 

`search(catalog_name: string): Request;`

I've tried the following definition files and run into similar issues with all of them:  
- This github repo (https://github.com/yathit/ydn-db/tree/master/misc)
- The main download page (https://dev.yathit.com/ydn-db/downloads.html)
- The DefinitelyTyped repo (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cc3d223a946f661eff871787edeb0fcb8f0db156/ydn-db/ydn-db.d.ts)

**Comment by yathit** [comment]
Thanks. updated.
