### ISSUE TITLE
Feature Request - Synchronous version of .put() and .add() methods

### ISSUE THREAD

**Issue by LeftPinkie** [yathit/ydn-db#103]
Currently, `.put()` and `.add()` methods of ydn.db.Storage is asynchronous. This is a request for a synchronous version of these methods, either as separate methods or an optional parameter.

Class: **ydn.db.Storage**
Methods: **.add()** and **.put()**

**Comment by yathit** [comment]
According to indexedDB API version 1, only asynchronous version will be supported. So it is not possible to provide synchronous methods by the library.
