### ISSUE TITLE
Example of deleting DB and recreating when page is loaded/reloaded but not when refreshed

### ISSUE THREAD

**Issue by MB34** [yathit/ydn-db#105]
Attached is the animals demo that will delete the database if the page is being loaded or reloaded but not refreshed.

This allows you to have fresh data each time the user comes to the page.

I have also shown how to modify the `renderResult()` function to be used when you call `this.db.search()` and when you call `this.db.values()` and added a `getAll()` function to print all records.

[mb34_animals.zip](https://github.com/yathit/ydn-db/files/307335/mb34_animals.zip)

**Comment by yathit** [comment]
👍
