### ISSUE TITLE
valuesOf(IndexIterator) with webstorage never dispatch a response

### ISSUE THREAD

**Issue by mehdirande** [yathit/ydn-db#111]
Hi, 

When using valuesOf with sessionstorage or localstorage, the deferred object seems to be lost if there is no results.
Here is a sample code :
`
var db = new ydn.db.Storage('bugfix111, { stores : [{name: 'item', keyPath: 'id', indexes : [{name:'type', keyPath:'type'}]}]},  {mechanisms: ['localstorage']});

var it = ydn.db.IndexIterator.where('item', 'type', '=', 'folder');

db.values(it).then(function(r) {
        console.log(r);
}, function(e) {
        console.log(e);
});
`

I'm I doing something wrong or is this possibly a bug ? If it's a bug I'll give a try to submit a PR.

Thanks

**Comment by mehdirande** [comment]
Duplicate of #90

**Comment by yathit** [comment]
Thanks @mehdirande PR welcome.
