### ISSUE TITLE
iOS 8 not working at all.

### ISSUE THREAD

**Issue by JerryLumpkins** [yathit/ydn-db#23]
Safari in iOS 8 is not recognizing the ydn plugin at all. Have you been able to identify the issues? And do you have any time frame in mind for releasing an update that will work with iOS 8?

**Comment by rosshadden** [comment]
@yathit You said:  "You can still use ydn-db for indexeddb in safari, if your application is already aware of those bugs."  My app does not use multi-store transactions or key generations.

How do I tell ydn to use the same default fallback array (`['indexeddb', 'websql', 'localstorage', 'sessionstorage', 'userdata', 'memory']`) but to let safari use indexedDB if present?

**Comment by yathit** [comment]
Please use rel 1.1.4 (just updated) and provide your preference (as you wrote above) in instantiating `ydn.db.Storage`. The default don't include 'indexeddb' for `Safari` browser.
