### ISSUE TITLE
Native promises

### ISSUE THREAD

**Issue by arcanis** [yathit/ydn-db#31]
Hi,

I see you're using Goog's Deferred. Could it be possible to use native promises instead, when available (and fallback on Deferred when they're not, as in IE) ? The main issue is that their API are not identical (for example, Promises have a 'catch' method while Deferreds don't), so a Deferred wrapper would be required.

I think it could only improve the library and keep it up-to-date with the latest browser evolutions. I'm currently working on a Promise-heavy application, and it's a bit weird to have some places where I know that I'm working with something that look like a Promise, smell like a Promise, but is not a Promise and will crash the code if used wrong :)

**Comment by yathit** [comment]
Native promise is not compatible with indexeddb auto commit, which run at the end of event loop but not in next event loop. See detail discussion in [webapp mailing list](https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0133.html).
