### ISSUE TITLE
Firefox 36 Beta bug

### ISSUE THREAD

**Issue by nullrocket** [yathit/ydn-db#40]
Auto updates just moved me to FF 36 Beta, which caused my application to stop working. I tried out the demo at http://yathit.github.io/ydndb-demo/todo/todo.html and it has the same error to the console as follows.   I am searching FF bugs to see if there are any reports but thought I would give you a heads up.

```21:6:59.179

log:open request to database "todo_2"  cause error of UnknownError

21:6:59.180 log:undefined
21:6:59.181 log:Storage:todo_2: opening fail
21:6:59.182 log:Storage:todo_2: database connection fail undefined
UnknownError	

...aultPrevented)){e.q.close();e.q=null;var b=Error();b.name=a.type;e.Fa(b)}},f.cal...

ydn.db-dev.js (line 257)
21:6:59.197 log:Purging 0 transactions request.

**Comment by yathit** [comment]
I just try out Firefox 36 Beta 1 on OS X and it is working fine. 

Please see issue on https://github.com/yathit/ydn-db/issues/33 The issue reporter allow me to use his computer remotely. I find the problem is localized version of Firefox is having issue.

**Comment by nullrocket** [comment]
I am having the issue on Win 8 on several machines, I reverted back to 35 and it cleared up, I did a clean install on another Win 8 machine also with 36 and still had the problem.  OSX is working fine here also.  I think it is probably a Win only FF bug, hopefully it only lasts for this beta revision!  Thank you for taking a look.

**Comment by nullrocket** [comment]
Now that FF 36 is out of beta the error is back again.

**Comment by yathit** [comment]
Please reopen if broken again.
