### ISSUE TITLE
warning: "'webkitIDBRequest' is deprecated. Please use 'IDBRequest' instead."

### ISSUE THREAD

**Issue by hliyan** [yathit/ydn-db#45]
Browser: Chrome Version 41.0.2272.76 (64-bit)
"ydn.db": "~1.0.3"

encountered at load time

NOTE: i'm using browserify to concatenate ydn-db into a single minified vendor bundle

**Comment by yathit** [comment]
It is not used, but for sniffing

**Comment by hliyan** [comment]
ah, great. i'll close the issue.
