### ISSUE TITLE
bower.json main is wrong

### ISSUE THREAD

**Issue by astroanu** [yathit/ydn-db#47]
Hey, they file defined in bower.json as main is not there. It should be "jsc/ydn.db-dev.js" not "jsc/ydn.db-npm-dev.js",

**Comment by yathit** [comment]
npm, bower does not fit with closure tool chain. I have to get rid of them. Thanks for report.

**Comment by astroanu** [comment]
wait, so if i'm using bower and gulp inject on my angular project how do i install ydn with bower and how will gulp know which js to include ?
