### ISSUE TITLE
Provide non-minified version

### ISSUE THREAD

**Issue by FMCorz** [yathit/ydn-db#56]
It can be really handy at times to have the non-minified version.

Please, could you ship them?

**Comment by yathit** [comment]
Rubbish issue, don't do again.

**Comment by FMCorz** [comment]
I'm sorry if that looks rubbish to you, is it provided somewhere or you just don't want to do so?

**Comment by yathit** [comment]
You can find concatenated js as "raw" in download page. You can clone repo and run unit test, they are run in raw files without concatenation.

**Comment by FMCorz** [comment]
Ok, found them.

For further reference: you need to login to see the raw file.
