### ISSUE TITLE
Restrict on iterators

### ISSUE THREAD

**Issue by holbrookab** [yathit/ydn-db#60]
Hi.  Very helpful library, thank you!

In this link:
https://dev.yathit.com/api/ydn/db/iterator.html

There is mention of a restrict() function, however when I try and use it, the function is not found.  Is there a particular module I need to enable that functionality?

**Comment by yathit** [comment]
Thanks, it was a old method, now I have remove from the API doc.

The new way is to use [key joining](https://dev.yathit.com/ydn-db/doc/query/join-query.html).
