### ISSUE TITLE
"npm install ydn.db" doesnt install

### ISSUE THREAD

**Issue by kakadiya91** [yathit/ydn-db#63]
```bash
npm WARN package.json karma-mocha@0.1.10 No README data
npm WARN package.json node-libs-browser@0.5.0 No repository field.
npm WARN package.json val-loader@0.5.0 No repository field.
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ydn.db" "--save"
npm ERR! node v0.10.36
npm ERR! npm  v2.3.0
npm ERR! code E404

npm ERR! 404 Not Found: ydn.db
npm ERR! 404 
npm ERR! 404 'ydn.db' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'x'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!   npm-debug.log
```

I also tried  "npm install ydn/db",  "npm install ydn-db",  "npm install ydndb",  "npm install ydn". None of them seems to work.

**Comment by fatso83** [comment]
You didn't try the simplest thing: searching for it? It is the top hit at npmjs.com. It is called `ydn.base`. YMMV - I just happened to come by.

**Comment by fatso83** [comment]
It does not seem to live on NPM, so why should it work? You can just simply specify the github repo in your package.json. Add it like this `npm install --save-dev yathit/ydn-db`. You can optionally specify a version tag or commit id, but refer to the npm docs for more. Know your tools.

**Comment by kakadiya91** [comment]
@fatso83 , I got that, this issue was meant to address pushing to NPM, which should be the case given this commit: https://github.com/yathit/ydn-db/commit/a546bd23b1d6324499525a465d38e6ac25e6477b. Anyway, we went ahead with native IndexedDB for different reasons.

**Comment by yathit** [comment]
@fatso83 @kakadiya91 `npm install ydn.db` should work now. I have add compiled js file and publish them.

**Comment by kakadiya91** [comment]
@yathit thanks, appreciate it! :)
