### ISSUE TITLE
Where is the documentation repository?

### ISSUE THREAD

**Issue by merriam** [yathit/ydn-db#68]
I'm sorry if I managed to miss an obvious location.   I would like to propose edits to pages such as https://dev.yathit.com/ydn-db/doc/query/cmpidx.html.  In which gitHub repository should I search?

**Comment by yathit** [comment]
Hi @merriam website content are in https://github.com/yathit/ydndb-website-content The page is in https://github.com/yathit/ydndb-website-content/blob/master/ydn-db/doc/query/cmpidx.markdown 

Feel free to edit. I will update after your edition. Thanks.
