### ISSUE TITLE
Building YDN

### ISSUE THREAD

**Issue by cristi-badila** [yathit/ydn-db#69]
Hi, my name is Cristian and I've been trying to use ydn-db with fulltext on a project. The issue that I'm having is that on the [official downloads page](https://dev.yathit.com/ydn-db/downloads.html), I can't find a prebuilt package with the modules I need (support for indexedb, websql and fulltext). I tried cloning all the repositories on which ydn has dependencies and tried building it by myself using ant the existing targets but that didn't seem to work. The first thing I did was I ran `ant deps`, `ant ydn-base.deps` and `ant compile-main-dev` for ydn-db. Everything seemed to work although I'm not sure if all the modules are included by default. I then ran  `ant compile-dev` for ydn-db-fulltext which also seemed to worked. When I included the resulting files (`ydn.db-dev.js` and `ydn.db-crud-core-text-e-dev.js`) in a project the search functionality did not work. ('search was not defined'). Also when I ran the tests for ydn-db I got multiple failing specs. Could anybody share some more details on how to properly build ydn-db with the fulltext module?

**Comment by yathit** [comment]
Buy [subscription](https://www.yathit.com/shop/ydn-db-subscription.html) to get custom build. Yearly subscription includes build script.
