### ISSUE TITLE
Query with where & order always resolves with empty result

### ISSUE THREAD

**Issue by dave-trudes** [yathit/ydn-db#70]
Hi there,
I'm using ydn at version 1.1.2 and have following schema:

```javascript
stores: [{
  name: 'data',   
  keyPath: 'id',
  type: 'NUMERIC',

  indexes: [
    {
       name: 'status',
       keyPath: 'status',
        type: 'NUMERIC'
    },
    {
       name: 'status, location.name',
       keyPath: ['status', 'location.name']
     }
   ]
}]

// Insert values
db.put(data, [...])
```

After inserting values, the 'status, location.name' table is populated accordingly. If I then want to execute the following query, the promise always resolves empty.

```javascript
db.from("data")
  .where("status", "=", 2)
  .order('location.name', true)
  .list()
  .done(resolve).fail(reject);
```

**Comment by yathit** [comment]
It looks ok. Could you post runnable code in jsbin?

Thanks

**Comment by dave-trudes** [comment]
Thank you for your quick reply. Here is the jsbin: http://jsbin.com/cewexewome/edit?js,console,output

**Comment by nevech** [comment]
I have the same problem if my store have indexes and used localstorage driver.

Test case:
* db.put(data)
* db.values('store')

Returns data without the first operation, but table is populated.

**Comment by yathit** [comment]
Thanks @dave-trudes please update to 1.1.5 for this fix.

@nevech websql and localStorage adaptor are still failing some tests with compound index. I will fix later.
