### ISSUE TITLE
pass parameters into done callback

### ISSUE THREAD

**Issue by 0090491** [yathit/ydn-db#72]
How can I pass extra parameters into the done callback function for example i need to pass the array value into the done function something like this

 for (i = 0; i < arrNewLinesText.length; i++) {
            transcriptTextDB.indexedDB.db.get("tableName", "lineID").done(function (record, arrNewLinesText[i]) {
                  //inside the done do something with array element arrNewLinesText[i];
             });

**Comment by yathit** [comment]
Use  [underscore bind](http://underscorejs.org/#bind) method.
