### ISSUE TITLE
Non-minified version of YDN-DB 

### ISSUE THREAD

**Issue by gabrielmaldi** [yathit/ydn-db#77]
Could you provide a single-file version of YDN-DB which is non-minified, contains comments, etc.? This is very helpful while developing because it allows stepping into the source code. It would also allow for not including the source map (which in fact doesn't work, at least in Chrome, because it contains references to files in `raw.github.com`).

Thanks!

**Comment by yathit** [comment]
Sorry, I could not help with concentrating file. My suggestion for library developer is, load raw files as in unit test files. It will load hundred of files, but never give trouble and always run fast. With concentration, there is extra step. 

For library user, use minified file. Don't debug, the library is *pretty bug free*. If there is a bug, file an issue, preferable with reproducible steps or unit test.

**Comment by gabrielmaldi** [comment]
Thank you for your answer. One more question: what's the difference between these two files:

<img width="397" alt="screen shot 2015-08-19 at 12 39 13 pm" src="https://cloud.githubusercontent.com/assets/3728897/9360904/51f19508-466f-11e5-840a-229511f5d110.png">

**Comment by yathit** [comment]
dev version have assertion and helpful message.
