### ISSUE TITLE
list() does not consider offset number

### ISSUE THREAD

**Issue by Barnadeep** [yathit/ydn-db#78]
Thanks yathit for this great library. Can you please help with the below issue?

As per documentation @ https://dev.yathit.com/api/ydn/db/query.html  the list method limits the number of results in a query to n, and if the query is run again would return the next n, then next n and so on.

But this is not working, each time I run a query using list, it returns the first n results. Is there a workaround for this? Can we pass an offset to the list method so that will return n results after ignoring the first m?

**Comment by yathit** [comment]
Can you show a runnable code that is  not working?

I tried in [getting started page](http://dev.yathit.com/ydn-db/doc/setup/) instruction and working correctly.

![image](https://cloud.githubusercontent.com/assets/2137932/9685152/f32efc3a-534e-11e5-818a-ebd08191e64a.png)
