### ISSUE TITLE
Default query limit not documented

### ISSUE THREAD

**Issue by cdaringe** [yathit/ydn-db#80]
Hello!

I must start by saying _thank you_!

Here, there's a default query limit being applied: https://github.com/yathit/ydn-db/blob/master/src/ydn/db/query/query.js#L211

However, here: https://dev.yathit.com/api/ydn/db/query.html , it states that query limit is optional.  This was unknowingly restricting my query!  Although `limit` is optional I felt a mention of the implicitly applied limit would be beneficial.

Thanks!

:)

**Comment by yathit** [comment]
Thanks. I have updated the doc. 

That is the most surprise about ydn-db api. I really don't like surprise, but thinks that always having a limit on query is a good practice.
