### ISSUE TITLE
iOS 9 and Safari in El Capitan are stopping at 5MB even after prompting for 50MB

### ISSUE THREAD

**Issue by JerryLumpkins** [yathit/ydn-db#83]
Our web application stops loading data into the local data store in both Safari and Chrome in iOS9 and in the El Capitan version of Safari at 5MB. I see no errors in the javascript console.

In Windows with Edge, IE11, Chrome and Firefox; Linux with Chrome and Firefox; Android devices with Chrome; and in iOS8, and earlier versions of OSX running Safari everything works fine.

Have you starting testing with these products? Any new information you can share about workarounds would appreciated.

**Comment by yathit** [comment]
This is know issue. Please find in internet.

**Comment by JerryLumpkins** [comment]
I've been searching the internet for information about it. Could you post a link to what you have found?

**Comment by JerryLumpkins** [comment]
When you say this is a known issue, are you sure we're talking about the same thing?

We have no problems with iOS8. It works fine. The problem is only with iOS9, the very latest Safari. I see nothing anywhere on the Internet discussing this. Would you please post links to what you have found?

**Comment by JerryLumpkins** [comment]
This issue should not have been marked as closed even if you don't plan on doing anything about it.

**Comment by yathit** [comment]
Please proof your claim by a simple test case. 

You can run unit tests http://dev.yathit.com/ydn-db/doc/example/unit-tests.html 

If you want to solve YOUR problem by talking, please do in forum, this is not the right place.

**Comment by JerryLumpkins** [comment]
We have many devices that are running iOS8, and our product works fine. On ALL devices running iOS9, it doesn't work at all. I will provide you with more information, but I expect you to be looking at your product in iOS9, and not swearing at me because I haven't solved your problem.

**Comment by JerryLumpkins** [comment]
We just browsed to your list of unit tests in iOS9 and ran all the unit tests. 3 of them fail. Have you even tried to run your own unit tests on an iOS9 device? We also get errors in the latest Safari running OS X Yosemite. When did you run your own unit tests against the newest versions of the iPad and Mac operating systems?

**Comment by JerryLumpkins** [comment]
This issue is neither invalid nor closed.

**Comment by yathit** [comment]
Hi @JerryLumpkins Yes. We know Safari has a lot of problem. When writing app for Safari, we keep those failing test in mind.

If you have specific issue in iOS 9, please reopen the issue. I will take a look.

**Comment by yathit** [comment]
IndexedDB is not available inside webworkers 

https://bugs.webkit.org/show_bug.cgi?id=149953
