### ISSUE TITLE
iOS 9 not working

### ISSUE THREAD

**Issue by JerryLumpkins** [yathit/ydn-db#84]
After upgrading from iOS8 to iOS9, all the calls to ydn-db are failing. I have searched the internet and found one reference to a problem: http://stackoverflow.com/questions/33081419/values-function-in-ydn-db-not-working-in-safari-and-ios9

Other than that, there is no mention anywhere on the Internet of this issue. We have multiple clients that have upgraded their iPads to iOS9, and they are now not able to use them with our product. Do you have a solution for this? You marked my previous issue report at a known issue. If it is, we would like to know what you plan to do about it. Or at least point out a link on the Internet that mentions it. This is NEW to iOS9. It has nothing to do with any issues reported prior to its release.

**Comment by yathit** [comment]
Please don't create an issue if you don't have solid proof about the issue. Definitely I don't entertain everyone shit here.

**Comment by JerryLumpkins** [comment]
Why don't you try running your unit tests on an iOS9 device yourself? It fails miserably. Please don't blow off my issues without investigation.
