### ISSUE TITLE
iOS9 fails the unit tests on this site.

### ISSUE THREAD

**Issue by JerryLumpkins** [yathit/ydn-db#85]
When you run the unit tests specified on this site using an iPad running iOS9 it fails at least 3 of them. It also fails in the latest version of 10X.

Let us know when you've fixed your product.

**Comment by yathit** [comment]
These failing test are know issues and no plan to fix. The reason is it is not worth fixing them. We have tried as much possible. The suggested workaround is to use WebSQL in Safari. It is OK in most app.

**Comment by JerryLumpkins** [comment]
![image](https://cloud.githubusercontent.com/assets/5314886/10446963/ebc12c9e-714d-11e5-803f-ffe66d3b6ac3.png)

**Comment by JerryLumpkins** [comment]
You know, we are 4 days into no solution for any aspect of the fact that your product fails miserably in iOS9. Have you even tried to use it?

**Comment by yathit** [comment]
The miserable situation is the same if you use IndexedDB natively.

**Comment by JerryLumpkins** [comment]
We are not using indexeddb for this.:


var options = {
    mechanisms: ['websql'], // default ordering
    size: 50 * 1024 * 1024  // 50 MB 
};
var IEOption = {
    size: 50 * 1024 * 1024  // 50 MB 
};

var iOS = (navigator.userAgent.match(/(iPad|iPhone|iPod)/g) ? true : false);
var macOsx = (navigator.userAgent.match(/(Mac)/g) ? true : false);
var iOSVer8 = (navigator.userAgent.match(/(OS 8)/g) ? true : false);
var IE11 = !!navigator.userAgent.match(/Trident.*rv[ :]*11\./);

if (iOS == true || macOsx == true) {
    if (iOSVer8 == true) {
        db_mob_audit = new ydn.db.Storage('idb_mob_auditor', schema, options);
    }
    else if (macOsx == true) {
        db_mob_audit = new ydn.db.Storage('idb_mob_auditor', schema, options);
    }
    else {
        db_mob_audit = new ydn.db.Storage('idb_mob_auditor', schema);
    }
}else {
    if (navigator.userAgent.search("IE") >= 0 || IE11 == true) {
        db_mob_audit = new ydn.db.Storage('idb_mob_auditor', schema, IEOption);
    } else {
        db_mob_audit = new ydn.db.Storage('idb_mob_auditor', schema);
    }
}

This code was written prior to iOS9.
We have added extra logic to determine if the os is iOS9, and use the appropriate options for it also. It just fails. We have been working with this for almost 3 years now. We aren't making some beginner's mistake.

**Comment by yathit** [comment]
Have you try removing `size` option? Probably it is not allow in iOS9.

**Comment by JerryLumpkins** [comment]
We need the space. The 50MB is a serious constraint that we keep hoping they will get rid of. On Android devices I have up to 20 percent of the available disk space.

**Comment by JerryLumpkins** [comment]
If we were to only have 5 MB, we can't do anything we are trying to do. Our web application uses apache and client side data storage to allow the user to continue to use our product (conducting audits) when there is no internet connection.

**Comment by yathit** [comment]
Suggested approach for opening `ydn.db.Storage` is just open without any options. Let the library select best options.

**Comment by JerryLumpkins** [comment]
Will it make the correct decision to use WebSQL without being provided the option? That didn't work previously.

**Comment by yathit** [comment]
@JerryLumpkins don't worry about storage limit option, it never get approve from W3C. You will get the storage as platform provide. So if user approve, your app will get 50 MB in iOS.

**Comment by yathit** [comment]
> Will it make the correct decision to use WebSQL without being provided the option?

Yes. If you use codova with Sqlite plugin, Sqlite is preferred over WebSQL. So there are too many stuff. Let the library do.

**Comment by JerryLumpkins** [comment]
We don't want to keep asking the user to increase data storage space like 4 times during a single download. That's why we are asking for the max up front. IF you think it will work better without the hints we will try. I had a company buy $50,000 worth of iPads, and fly a team of auditors to Brazil on ly to find out that those running iOS9 (over half) wouldn't work.

**Comment by yathit** [comment]
Please close if your issue is resolved.

**Comment by JerryLumpkins** [comment]
I will explore changing the option, and let you know what we find.

**Comment by yathit** [comment]
If you serious need 50 MB upfront, some people are writing dummy database the require storage. After then open the real database. So that is ugly workaround, since WebSQL silently fail (yes, silently fail) even if user approve the storage.

**Comment by JerryLumpkins** [comment]
I hear what you are saying, except that this has been working reliably for us for more than a year.

**Comment by swapnil0545** [comment]
@yathit I have been working along with @JerryLumpkins on this issue.
Webworker specific issue  :
Firstly I think we should see why the library is not working when we pass in the options parameter to the Storage 
Demo : http://52.24.87.119/demo/index2.html
This issue is there in chrome as well.
If we do not pass in the options parameter and let it choose for itself then it doesn't work on Safari but does on Chrome.
Demo : http://52.24.87.119/demo/index.html

**Comment by yathit** [comment]
I think if you want to open more than 5MB in ios, you have to open database in user event, such as button click callback.  Could you try out? Thanks.

**Comment by swapnil0545** [comment]
What we do is we create the schema from outside of the worker page also, from there it does ask for the storage prompt of 100mb on Mac Safari 9 and earlier versions. But we want to access the same schema in webworker also. But it is not able to open and use it.

**Comment by yathit** [comment]
It should be able to open in web worker if user already granted for the
origin.

**Comment by swapnil0545** [comment]
Yes, but at this moment I am not able to create a schema with websql .
It doesn't work when I pass     
var options = {
	mechanisms: ['websql']
    };

http://52.24.87.119/demo2/index.html

**Comment by JerryLumpkins** [comment]
Yahit,

We are not wanting to ask for more than the 50 MB in iOS. But we want to ask for exactly 50 MB up front. We don't want the user to be prompted for 5, 10, and then 25. We want to have them approve the maximum allowed up front, and then not bother them any more.

**Comment by JerryLumpkins** [comment]
Yahit,

We are not wanting to ask for more than the 50 MB in iOS. But we want to ask for exactly 50 MB up front. We don't want the user to be prompted for 5, 10, and then 25. We want to have them approve the maximum allowed up front, and then not bother them any more.

**Comment by yathit** [comment]
Please open again if more information available.

My suggestion is use in main thread. Since all DB request are async (no UI block), background worker is not necessary.

**Comment by yathit** [comment]
indexedDB API support in web worker is coming to Safari (and iOS?). https://developer.apple.com/safari/technology-preview/release-notes/
