### ISSUE TITLE
Functionality in ydn.db is missing

### ISSUE THREAD

**Issue by colmsjo** [yathit/ydn-db#88]
I'm using `ydn.db-is-core-qry.js`, downloaded last week.

A lot of the functionality listed in the documentation is missing under the object `ydn.db`.
I cannot for instance find `ydn.db. KeyIterator ` or `ydn.db. ValueIterator`. I've attached a screenshot from Firefox.

<img width="246" alt="skarmavbild 2015-11-08 kl 18 53 34" src="https://cloud.githubusercontent.com/assets/1313294/11021672/139a36dc-864a-11e5-92e9-0178bb8d8b5d.png">

**Comment by yathit** [comment]
Ask question in stackoverflow.
