### ISSUE TITLE
Latest version of ydn.db and bulk upload data in ydn.db 

### ISSUE THREAD

**Issue by yogeshmahajan** [yathit/ydn-db#89]
Hi,

I am using encrypted ydn.db, version "ydn.db-is-core-crypt-cur-dev.js" for my application and its working fine for me. My concern is if I want to use latest version of encrypted ydn.db do it effects my existing data stored in ydn.db or it will be easy for me. So if there is any latest vesion available for encrypted ydn.db please provide it.

Also my second concern is that what is limits for data to be stored in ydn.db  tables. because I am storing minimum thousands of data objects having up to 15 attributes in one table, and sometime facing issue to retrieve data from ydn.db when there are thousands of record. so how we can get information of how much data can we stored in ydn.db tables. or how can we increase the limits of ydn.db storage.

Again we are storing data as per tuples in ydn.db table. If we want to store multiple tuples at a time with multiple ID and wants to fetch these multiple data with single call from ydn.db, do it is possible in current scenario. because storing multiple tuples against ID in ydn.db we need to use loop which downs performance of my application.

**Comment by yathit** [comment]
There is performance improvement in encryption and some fix in encrypting international char.

I would suggest ask in StackOverflow or [purchase premium support](https://www.yathit.com/shop/ydn-db-subscription.html).
