### ISSUE TITLE
Get Values with IndexValueIterator and Mechanism localstorage without items don't resolve promise

### ISSUE THREAD

**Issue by miquellaboria** [yathit/ydn-db#90]
When I get Values from localstorage using IndexValueIterator and I don't have any items on the store, the promise never resolve.

**Comment by yathit** [comment]
Sorry no plan to fix now.

**Comment by mehdirande** [comment]
I had to make a patch into ydn-base and ydn-db to solve this issue. I hope that it was the right way to fix it (cf PR #1 of ydn-base and PR #112 of ydn-db).
