### ISSUE TITLE
no example of how to use ydn.dB module in browserify bundled project

### ISSUE THREAD

**Issue by kiddhustle** [yathit/ydn-db#93]
The ydn.dB module is packaged as closure library module. This doesn't seem to be compatible with browserify which uses CommonJs.

A working example in the docs would be helpful.

**Comment by yathit** [comment]
Sorry, we do not have example. All of our projects use raw js code with closure library. 

If you use closure compiler, it supports CommonJS module.

**Comment by kiddhustle** [comment]
OK I think figured it out. Simply requiring the module (and not assigning it to a variable )will make it global inside the module that you're requiring it from.

Thanks for the response all the same.
