### ISSUE TITLE
Support for Bower dependency management

### ISSUE THREAD

**Issue by bennyn** [yathit/ydn-db#94]
Hello, I want to retrieve the latest version of "ydn-db" via [Bower](http://bower.io/).

The dependency entry in my `bower.json` is this:

```json
"dependencies": {
  "ydn.db": "git://github.com/yathit/ydn-db.git#v1.3.3"
}
```

But when I run `bower install` then I don't get files like `ydn.db-i-crud.js`. :cry: 

Do you plan to host a second repository to distribute ydn-db via Bower or can you please add the minified files to a `dist` directory in this repository to support the dependency management via Bower?

**Comment by yathit** [comment]
Yes, please go ahead with publishing your bower repo.
